### PR TITLE
Build for more platform

### PR DESCRIPTION
**Pull request by Brooooooklyn**
Build pipeline passed: https://github.com/Brooooooklyn/source-map/actions/runs/1142052971

Close https://github.com/parcel-bundler/source-map/issues/70

### CODE REVIEW

**Review by DeMoorJasper — APPROVED** [review]
This is amazing, thank you so much

**Comment by Pitbi** [comment]
Hey,

Will this update soon be used by a newer version of parcel on npm?

Thx

**Comment by Pitbi** [comment]
Hello,

I updated the (nested) dependencies, now I have this error:
```

Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /app/node_modules/@parcel/transformer-js/parcel-swc.linux-arm64-gnu.node)
  Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
  (required by
  /app/node_modules/@parcel/transformer-js/parcel-swc.linux-arm64-gnu.node)
  at Object.Module._extensions..node (node:internal/modules/cjs/loader:1168:18)


```

Still with the configuration: docker / linux system on a Mac M1 chip.

An idea?


Thx

**Comment by mischnic** [comment]
This PR wasn't released yet on npm. So this is caused by something else

**Comment by dBitech** [comment]
Can FreeBSD (freebsd-x64) be added to the list of platforms?

**Pull request merged**
