### PR TITLE
Add wasm frontend

### PR DESCRIPTION
**Pull request by mischnic**
(Don't ask me why I can't push to this repo itself)

All tests pass.
```
 32K source-map.js
151K source-map.wasm
```

The main question: the native version is completely synchronous, but loading the wasm bundle is asynchronous. For now, I've added a `init` promise export; not sure if there is a better solution.

### CODE REVIEW

**Comment by mischnic** [comment]
Everything should work now, but I'm having trouble installing emscripten on azure. I don't know where to clone the sdk to.

**Comment by mischnic** [comment]
wasm can't access JS memory (but JS can access wasm memory), so every time we pass a buffer to wasm it has to be copied. I think this is the main reason why it's slower:

```
$ node ./bench/run.js
consume vlq mappings 34496.64 opts/sec (mean: 0.029ms, stddev: 0.01ms, 250 samples)
consume flatbuffer 34672 opts/sec (mean: 0.029ms, stddev: 0.013ms, 250 samples)
consume JS Mappings 2358.28 opts/sec (mean: 0.424ms, stddev: 0.187ms, 250 samples)
Save buffer 35890.3 opts/sec (mean: 0.028ms, stddev: 0.021ms, 250 samples)
extend map 32695.26 opts/sec (mean: 0.031ms, stddev: 0.015ms, 250 samples)
stringify 24577.5 opts/sec (mean: 0.041ms, stddev: 0.029ms, 250 samples)
combine 1000 maps using flatbuffers 46.58 opts/sec (mean: 21.468ms, stddev: 4.792ms, 250 samples)
combine 1000 maps using vlq mappings 30.81 opts/sec (mean: 32.461ms, stddev: 7.671ms, 250 samples)
combine 1000 maps using flatbuffers and stringify 21.07 opts/sec (mean: 47.458ms, stddev: 16.245ms, 250 samples)
$ BACKEND=wasm node ./bench/run.js
consume vlq mappings 4134.81 opts/sec (mean: 0.242ms, stddev: 0.209ms, 250 samples)
consume flatbuffer 9536.27 opts/sec (mean: 0.105ms, stddev: 0.176ms, 250 samples)
consume JS Mappings 842.98 opts/sec (mean: 1.186ms, stddev: 0.936ms, 250 samples)
Save buffer 16317.34 opts/sec (mean: 0.061ms, stddev: 0.058ms, 250 samples)
extend map 11668.46 opts/sec (mean: 0.086ms, stddev: 0.057ms, 250 samples)
stringify 1650 opts/sec (mean: 0.606ms, stddev: 0.464ms, 250 samples)
combine 1000 maps using flatbuffers 86.81 opts/sec (mean: 11.519ms, stddev: 10.78ms, 250 samples)
combine 1000 maps using vlq mappings 8.82 opts/sec (mean: 113.37ms, stddev: 29.67ms, 250 samples)
combine 1000 maps using flatbuffers and stringify 106.41 opts/sec (mean: 9.397ms, stddev: 5.568ms, 250 samples)
```

**Comment by DeMoorJasper** [comment]
@mischnic damn that benchmark is disappointing. I guess there's nothing we can really do about it, I'll create a Full-JS version and test whether it's actually faster or slower

**Comment by mischnic** [comment]
I have no idea on how to get `${{ if eq(parameters.name, 'macOS') }}:` to be accepted.
The checks works for everything except macOS (where the steps are correctly skipped), but on macOS Azure complains `Unrecognized value: 'parameters'` 🤷‍♂

**Comment by mischnic** [comment]
Ok, everything works now.

The publish step for wasm is more of a guess.

**Pull request merged**
